### ISSUE TITLE
Feature Request for buffer around claims

### ISSUE THREAD

**Issue by Dreamthief01** [JayAvery/floristics#10]
While this seems to be doing a great job of not planting saplings within claims, it will still plant saplings right on the edge of claims and then the leaves can overhang.  

A nice feature would be having a configurable threshold such that when set at "5" for example, when trying to plant a sapling, the system would check if the block is on a protected claim, and then check if any blocks 5 blocks N S E W of that block are a protected block  

Just a thought if you run out of ideas.

**Comment by averixus** [comment]
Oh, this is a good point! It might not even need to be configurable really, it should be built-in that trees can't generate overhanging claims.
