### ISSUE TITLE
Feature request: WorldGuard support

### ISSUE THREAD

**Issue by SlimeDog** [JayAvery/floristics#13]
Please reconsider adding WG support. Easiest: no growth in regions with specified names.

**Comment by averixus** [comment]
For context, I've never used WorldGuard myself, but I'm looking into it now. I should be able to register a custom flag that can be applied to any WG region and then use that to check whether growth is allowed. For overlapping regions, it probably makes most sense to use the priority system in the same way as WG uses to decide e.g. if a player is allowed to build somewhere?

**Comment by SlimeDog** [comment]
Sounds good. Thanks.

**Comment by averixus** [comment]
Added!
