### ISSUE TITLE
Mushrooms grow on grass in sunlight

### ISSUE THREAD

**Issue by Cassolotl** [JayAvery/floristics#16]
![Screenshot 2019-11-30 at 13 23 48](https://user-images.githubusercontent.com/6607512/69901085-b90d1d80-1374-11ea-9883-8d82d1784c82.png)

**Comment by averixus** [comment]
Changed my mind! I'm considering this intended behaviour because it replicates the way mushrooms generate in vanilla. Sometimes they show up in 'invalid' locations (where they couldn't be placed manually), so I think it's reasonable to except the same with regrowth.

If anyone strongly feels the opposite, please comment again and I may reconsider!

**Comment by Cassolotl** [comment]
I think it is a bit different to plants appearing in invalid locations, because when that happens usually if you update a nearby block the plant realises it's invalid and drops. But also I don't mind that much. :)

**Comment by averixus** [comment]
You're right, I was wrong! Vanilla mushrooms do check light levels so this needs fixing to replicate that. :)

**Comment by averixus** [comment]
Now I'm unsure again :D In vanilla *some* mushrooms generate in all biomes restricted by light level (for caves), and some mushrooms generate in certain biomes only (swamp, mushroom fields, mega taiga) on the surface with no light level checks. So I'm back to thinking this is probably intended behaviour. But I'm open to being convinced, so I'll leave this undecided for a while.

**Comment by averixus** [comment]
I'm declaring this closed again, as of 2.4! I've added mushroom growth in low light levels in all biomes (as per vanilla). Surface mushrooms in bright light are valid vanilla behaviour in certain biomes (like mushroom fields), so I'm considering it acceptable even if they generate on blocks that are unusual for the biome (like grass).
