### ISSUE TITLE
Towny compatibility with Floristics.

### ISSUE THREAD

**Issue by jpotyka** [JayAvery/floristics#20]
I think the title says it all. 
It would be nice if you could turn automatic growth off to urban areas.
Further it would be handy if you could switch off the tree growth but grass etc. continues to grow.

**Comment by averixus** [comment]
> Further it would be handy if you could switch off the tree growth but grass etc. continues to grow.

By this do you mean as an overall plugin setting? That's already possible in the latest config - each plant type can be enabled or disabled individually.

Or do you mean as a setting per-town? That would be a much bigger overhaul but it's something I mayyy consider as a future goal.

**Comment by jpotyka** [comment]
Settings per town or even better, settings per protected chuck of the town.
Change the settings for each plant type would be nice. I don't want trees in my town to grow :)
Change the settings of the final plant density, maybe with a multiplier (e.g. 1= vanilla plant density, 2= double density).

**Comment by averixus** [comment]
Towny support has been added in 2.4! Per-claim config is still only a possible future consideration but I'm undecided. I don't intend to add options to adjust plant densities - my goal is only to replicate _vanilla_ generation as closely as possible.

**Comment by ghost** [comment]
Hi @JayAvery this is Siris one of the Towny contributors and implementor of the metadata system. I was wondering if it would be ok to advertise your plugin in the wiki under “plugins that use metadata”. It’s a great example of how to properly use towny metadata.

**Comment by averixus** [comment]
@suneettipirneni Wow I'd be honoured, please go ahead and refer to it! Thanks for asking. :)

**Comment by ghost** [comment]
@JayAvery its up

https://github.com/TownyAdvanced/Towny/wiki/Plugins-using-the-Towny-API#plugins-using-metadata

**Comment by jpotyka** [comment]
@JayAvery Thx for the fast update. "...but it's something I mayyy consider as a future goal." :+1:
