### ISSUE TITLE
Florisitics stopped working

### ISSUE THREAD

**Issue by bunfloof** [JayAvery/floristics#26]
Hi,

Floristics have stopped growing on my server. I have not noticed any growth for some week now. It was working fine last week and so on. I have reinstalled it a couple of times but still don't notice any growth. It is showing up in timings though: https://timings.aikar.co/?id=262cac6a96944ab6ab732c3c16db455b#plugins

I have set the level-seed in server.properties. I have WorldGuard for a very small area (6*6) and did allowed Floristics. I'm not sure if there's a plugin conflicting with it. The world once got corrupted once due to BSOD so I had to load it up from an earlier backup. 

EDIT: I uninstalled WorldGuard and it started growing again. It looks like WorldGuard was preventing it even though I allowed the Floristics flag and have WorldGuard for a very small area for spawn.

Thanks

**Comment by averixus** [comment]
Sorry it took me so long to get to this! I'm glad you got it working again, although it does sound like unexpected behaviour in the interaction with WorldGuard. Growth is denied inside regions by default unless the flag is set to allow, but growth should be allowed in locations that aren't in any region. Did you notice growth stopped even outside of all your WorldGuard regions?

**Comment by bunfloof** [comment]
Yes, there were no growth everywhere, even outside of my WG regions.

**Comment by averixus** [comment]
Thanks, that is strange. Can you tell me which versions of Spigot, WorldGuard, and Floristics you were using so I can investigate?

**Comment by bunfloof** [comment]
It was a long time ago since I uninstalled WorldGuard. I'm using a fork of spigot called [Paper](https://papermc.io/downloads), updated versions daily but they all produced the same results.
WorldGuard 7.0.2 (for MC 1.14.4 - 1.15.2)
Floristics 2.5

**Comment by averixus** [comment]
This should be fixed in [2.5.1](https://github.com/JayAvery/floristics/releases/tag/2.5.1)!
