### ISSUE TITLE
Feature Request Add sand to desert

### ISSUE THREAD

**Issue by Dreamthief01** [JayAvery/floristics#7]
Feature Request Add sand on top of sandstone, coal_ore, stone

**Comment by Dreamthief01** [comment]
Dirt too maybe?

Should also make Sand on / off a config option

DESERT,SAND:0,SANDSTONE,SAND:0,1
DESERT,SAND:0,COAL_ORE,SAND:0,1
DESERT,SAND:0,STONE,SAND:0,1
DESERT,SAND:0,DIRT,SAND:0,1

**Comment by averixus** [comment]
This is a nice idea! I'm just not sure whether it 'fits' with the overall aim, which is mostly plant-related. I'd appreciate feedback from other people about whether this should be available as a default setting, or just left as something which players can customise themself in plants.csv.
