### ISSUE TITLE
2x2 trees are sometimes incomplete

### ISSUE THREAD

**Issue by averixus** [JayAvery/floristics#9]
![image](https://user-images.githubusercontent.com/9510882/31078553-7c2ced5e-a77a-11e7-973a-14eec72a20c6.png)

**Comment by Dreamthief01** [comment]
Is the tree incomplete, or did it plant 4 saplings, then later plant a grass plant on top of the grass block which replaced one of the saplings?

**Comment by averixus** [comment]
It's either that, or that the sapling fails to plant when there is already grass in the way - it definitely seems to be something about one plant overriding another (I haven't yet had any reports or screenshots of a 2x2 failing with just an air gap).
